[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
remappings = [
  '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
  '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/'
]
solc_version = '0.8.28'
optimizer = true
optimizer_runs = 200
evvm_version = 'paris'
ffi = true

[fmt]
line_length = 120
multiline_func_header = 'attributes_first'
